# Generated by Django 2.2 on 2019-09-24 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='newAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('accountNumber', models.CharField(max_length=100)),
                ('balance', models.DecimalField(decimal_places=3, max_digits=10)),
            ],
        ),
    ]
